Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string           not null
#  description :text             not null
#

class Cat < ApplicationRecord
  ALL_COLORS = %w(black tabby beige white calico grey brown)
  validates :name, :sex, :birth_date, :description, presence: true
  validates :color, presence: true, inclusion: {in: ALL_COLORS}
  validates :sex, inclusion: {in: %w(M F)}

  def age
    Time.now.to_date.year - birth_date.year
  end
end

Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
  end

  def new
    @cat = Cat.new()
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cats_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cats_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
  end
end

Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats/app/helpers/cat_helper.rb
module CatHelper
end

Cats/app/helpers/cats_controller_helper.rb
module CatsControllerHelper
end

Cats/app/views/cats/_cat.html.erb
<table>
    <thead>
        <tr>
            <%=cat.name%>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Sex:</td>
            <td><%=cat.sex%></td>
        </tr>
        <tr>
            <td>Age:</td>
            <td><%=cat.age%></td>
        </tr>
         <tr>
            <td>Color:</td>
            <td><%=cat.color%></td>
        </tr>
        <tr>
            <td>Description:</td>
            <td><%=cat.description%></td>
        </tr>
    </tbody>
</table>

<%if action == :index %>
    <a href='<%=cat_url(cat)%>'> Inspect Cat </a>
<%elsif action == :show %>
    <a href='<%=cats_url%>'> Show all Cats </a>
    <br>
    <a href='<%=edit_cat_url(cat)%>'> Edit Cat</a>

<%end%>

Cats/app/views/cats/_form.html.erb
<%if action == :new%>
<%action_url = cats_url%>
<%button_text = "Create Cat"%>
<%elsif action == :edit%>
<%action_url = cat_url(cat)%>
<%button_text = "Edit Cat"%>
<%end%>

<form action="<%=action_url%>" method="post">
    <%if action == :edit%>
        <input type="hidden" name="_method" value="patch">
    <%end%>

    <label>
        Name: 
        <input type="text" name = "cat[name]" value="<%=cat.name%>">
    </label>
    <label>
        Sex:
            <input type="radio" name="cat[sex]" value="M" <%=cat.sex == "M" ? "checked" : ""%>> Male
            <input type="radio" name="cat[sex]" value="F"<%=cat.sex == "F" ? "checked" : ""%>> Female
     
       
       
    </label>
    <label>
        Birth Day: 
        <input type="date" name="cat[birth_date]" value="<%=cat.birth_date%>">
    </label>
    <label>
        Color: 
        <select name="cat[color]" >
                <%unless cat.color%>
                    <option disabled=true selected=true>--select color--</option>
                <%else%>
                    <option disabled=true>--select color--</option>
                <%end%>
            <%Cat::ALL_COLORS.each do |color|%>
                <option value="<%=color%>" <%=cat.color == color ? "selected" : ""%>><%=color.capitalize%></option>
            <%end%>
        </select>
    </label>
    <label>
        Description: 
        <textarea name="cat[description]"><%=cat.description%></textarea>
    </label>

    <input type='submit' value="<%=button_text%>">
</form>

Cats/app/views/cats/edit.html.erb
<ul>
    <li>
        <%= render 'form', cat: @cat, action: :edit%>
        <br>
    </li>
</ul>

Cats/app/views/cats/index.html.erb
<ul>
    <%@cats.each do |cat|%>
    <li>
        <%= render 'cat', cat: cat, action: :index%>
    </li>
    <br>
    <%end%>
</ul>

Cats/app/views/cats/new.html.erb
<ul>
    <li>
        <%= render 'form', cat: @cat, action: :new%>
        <br>
    </li>
</ul>

Cats/app/views/cats/show.html.erb
<ul>
    <li>
        <%= render 'cat', cat: @cat, action: :show%>
        <br>
    </li>
</ul>

Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>